from .road_tank_insertion import (
    NODE_CLASS_MAPPINGS as _TANK_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _TANK_NAMES,
)
from .road_mask_centerline import (
    NODE_CLASS_MAPPINGS as _CENTERLINE_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _CENTERLINE_NAMES,
)
from .road_orientation_v2 import (
    NODE_CLASS_MAPPINGS as _ORIENTATION_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _ORIENTATION_NAMES,
)
from .road_mask_border_fit import (
    NODE_CLASS_MAPPINGS as _BORDERFIT_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _BORDERFIT_NAMES,
)
from .sam3_all_roads import (
    NODE_CLASS_MAPPINGS as _SAM3ROADS_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _SAM3ROADS_NAMES,
)
from .road_quad_segments import (
    NODE_CLASS_MAPPINGS as _QUAD_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _QUAD_NAMES,
)
from .road_mask_complete import (
    NODE_CLASS_MAPPINGS as _COMPLETE_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _COMPLETE_NAMES,
)
from .passthrough import (
    NODE_CLASS_MAPPINGS as _PASS_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _PASS_NAMES,
)
from .insertion_controller import (
    NODE_CLASS_MAPPINGS as _CTRL_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _CTRL_NAMES,
)

NODE_CLASS_MAPPINGS = {
    **_TANK_CLASSES,
    **_CENTERLINE_CLASSES,
    **_ORIENTATION_CLASSES,
    **_BORDERFIT_CLASSES,
    **_SAM3ROADS_CLASSES,
    **_QUAD_CLASSES,
    **_COMPLETE_CLASSES,
    **_PASS_CLASSES,
    **_CTRL_CLASSES,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **_TANK_NAMES,
    **_CENTERLINE_NAMES,
    **_ORIENTATION_NAMES,
    **_BORDERFIT_NAMES,
    **_SAM3ROADS_NAMES,
    **_QUAD_NAMES,
    **_COMPLETE_NAMES,
    **_PASS_NAMES,
    **_CTRL_NAMES,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
