from .road_tank_insertion import (
    NODE_CLASS_MAPPINGS as _TANK_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _TANK_NAMES,
)
from .road_mask_centerline import (
    NODE_CLASS_MAPPINGS as _CENTERLINE_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _CENTERLINE_NAMES,
)
from .road_orientation_v2 import (
    NODE_CLASS_MAPPINGS as _ORIENTATION_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _ORIENTATION_NAMES,
)
from .road_mask_border_fit import (
    NODE_CLASS_MAPPINGS as _BORDERFIT_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _BORDERFIT_NAMES,
)

NODE_CLASS_MAPPINGS = {
    **_TANK_CLASSES,
    **_CENTERLINE_CLASSES,
    **_ORIENTATION_CLASSES,
    **_BORDERFIT_CLASSES,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **_TANK_NAMES,
    **_CENTERLINE_NAMES,
    **_ORIENTATION_NAMES,
    **_BORDERFIT_NAMES,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
