from .nodes import (
    NODE_CLASS_MAPPINGS as _NODES_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _NODES_NAMES,
)
from .alpha_bbox import (
    NODE_CLASS_MAPPINGS as _BBOX_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _BBOX_NAMES,
)
from .tank_scale import (
    NODE_CLASS_MAPPINGS as _SCALE_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _SCALE_NAMES,
)
from .tank_composite import (
    NODE_CLASS_MAPPINGS as _COMPOSITE_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _COMPOSITE_NAMES,
)

NODE_CLASS_MAPPINGS = {**_NODES_CLASSES, **_BBOX_CLASSES, **_SCALE_CLASSES, **_COMPOSITE_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**_NODES_NAMES, **_BBOX_NAMES, **_SCALE_NAMES, **_COMPOSITE_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
